# Generated by Django 5.1.4 on 2025-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
            preserve_default=False,
        ),
    ]
